import type { Metadata } from "next";
import { Inter, Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ThemeProvider } from 'next-themes'
import { TranslationProvider } from "@/context/i18n-store";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const noto_sans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-noto-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${noto_sans.variable} antialiased`}
      >
        <TranslationProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
            <footer className="text-center py-6 text-muted-foreground text-text-body-sm-size">
              © {new Date().getFullYear()} PCMate. All rights reserved.
            </footer>
          </ThemeProvider>
        </TranslationProvider>
      </body>
    </html>
  );
}
